server:
  port: 81

spring:
  application:
    name: tigetting

  datasource:
    url: jdbc:mysql://localhost:3306/tget?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #mapper-locations: classpath:/mapper/**/*.xml
  mapper-locations: classpath:mapper/UserMapper.xml
  type-aliases-package: com.ssafy.tigetting.user.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET:THIS_IS_A_LONG_RANDOM_PLAIN_SECRET_WITH_32+_CHARS_1234567890abcdef}
  access-token-validity-ms: 3600000

debug: true
